version: '3.7'

services:
  django-app:
    image: django-app
    container_name: django-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - web_data:/app
      
volumes:
  web_data:
  