version: '3'

services:
  django-app:
    image: programmer175/django-app:latest
    container_name: django-app
    ports:
      - "8000:8000"
    environment:
      USER: admin
      PASSWORD: admin@123!
      DB: postgres
    volumes:
      - web_data:/app
      - static:/app/staticfiles/
    depends_on:
      - pgdb


  pgdb:
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - pgdb

  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static:/static/
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - django-app

volumes:
  web_data:
  db_data:
  static:
