version: '3'

services:
  django-app:
    image: django-app
    container_name: django-app
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "8000:8000"
    volumes:
      - web_data:/app
    depends_on:
      - pgdb


  pgdb:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - pgdb

  nginx:
    container_name: nginx
    build: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django-app

volumes:
  web_data:
  db_data: