# Generated by Django 5.0.4 on 2024-04-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctor', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
