apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
      app: med-ease
  template:
    metadata:
      name: app-pod
      labels:
        name: app
        app: med-ease
    spec:
      containers:
        - name: app
          image: programmer175/django-app:latest
          volumeMounts:
            - mountPath: /app/staticfiles
              name: static
          ports:
            - containerPort: 8000
      volumes: 
        - name: static
          hostPath:
            path: /app/staticfiles/
            type: Directory
      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["python3", "manage.py", "migrate"]
